# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hndmrsh
email: samuel.hindmarsh@gmail.com
description: The personal portfolio website of Samuel Hindmarsh
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hndmrsh.github.io" # the base hostname & protocol for your site
twitter_username: hndmrsh
github_username:  hndmrsh

#jekyll_timeago:
#  depth: 1 # Level of detail
#  today: "Today"

collections:
  games:
    output: true
  software:
    output: true
  art:
    output: true
  music:
    output: true

# Build settings
markdown: kramdown
exclude: [working_files/]
